server:
  port: 18888

spring:
  datasource:
    username: root
    password: 1008610086
    url: jdbc:mysql://localhost:3306/fiddler?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gigass.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fast-pickUp-config:
  #发件人
  my-email-SMTP-host: smtp.qq.com
  my-email-account: 1547654938@qq.com
  my-email-password: siszzxatnlxyhcha
  #收件人
  to-email-account: 395650058@qq.com