server:
  port: 18888

spring:
  datasource:
    username: root
    password: 1008610086
    url: jdbc:mysql://localhost:3306/fiddler?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gigass.pojo